[package]
name = "delight_book"
version = "0.1.0"
authors = ["victoryang00 <yangyiwei2000@gmail.com>"]

[dependencies]
libc = "^0"
rand = "^0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"